### PR TITLE
Update leiningen to 2.8.0

### PR DESCRIPTION
**Pull request by cap10morgan**
I also removed the blank lines from the big `RUN` in the Dockerfiles because the latest version of Docker is warning that those will soon generate a build error.

### CODE REVIEW

**Comment by technomancy** [comment]
Out of curiosity, why is the whole `.../archive/2.8.0.tar.gz` file downloaded only in order to extract the single `lein-pkg` file out of it? Or am I misreading the Dockerfile?

Seems like it would make more sense just to download `lein-pkg` directly.

**Comment by cap10morgan** [comment]
@technomancy Good question. The answer might be "Because we've always done it that way." ;) I'll play around with it a bit.

**Comment by cap10morgan** [comment]
@technomancy Good suggestion! Just downloading `lein-pkg` works great (see 
0d768b5).

**Comment by technomancy** [comment]
Cool; thanks.

**Comment by cap10morgan** [comment]
This all look OK to you, @Quantisan?

**Comment by Quantisan** [comment]
@cap10morgan thank you!

**Comment by cap10morgan** [comment]
Sure thing, thank _you_! :)

**Comment by cap10morgan** [comment]
[Official images PR](https://github.com/docker-library/official-images/pull/3615)

**Pull request merged**
