### PR TITLE
Add JDK version 20 to build matrix & deprecate boot

### LINKED ISSUE #191: Can we get temurin 20 images?
We're starting to test locally with Temurin JDK 20 and it would be nice to update our CI pipeline to use `clojure:temurin-20-tools-deps` (we're on `clojure:temurin-19-tools-deps` right now).

### LINKED ISSUE #192: Deprecate boot?
Does anyone still use boot? Sounds like it's pretty moribund: https://github.com/Quantisan/docker-clojure/issues/191#issuecomment-1489538565 

It is also breaking in a few of its alpine image variants. I'm thinking maybe we stop building images with it starting with JDK 20 (which was just released and I'm working on adding to our build matrix now). JDK 21 will be the next LTS release coming out this fall, so it would be nice to get it out of there prior to that if we're going to do it.

There's also no reason people who use boot can't continue to build and publish their own Docker images. There just wouldn't be an official image for it any longer.

### PR DESCRIPTION
**Pull request by cap10morgan**
Closes #192 by removing all alpine boot variants (because they are breaking even on recent point releases of older JDKs) and all boot variants in JDK version 20+. Boot seems pretty moribund and supporting it is becoming more trouble than it's worth.

JDK version 20 has been out for a week or so and a user opened #191 to request JDK-20-based images (thank you, @seancorfield!) and it made me wonder if I could setup notifications to know when these new upstream releases happen. It turns out the Eclipse Temurin folks don't really have a way to do that yet but asked me to open [this issue](https://github.com/adoptium/adoptium-support/issues/751) for them to discuss it.

Closes #191 too.

### CODE REVIEW

**Comment by cap10morgan** [comment]
@Quantisan If you approve of the boot deprecation I'll update the README accordingly before merging.

**Comment by Quantisan** [comment]
> @Quantisan If you approve of the boot deprecation I'll update the README accordingly before merging.

yes please!

**Comment by cap10morgan** [comment]
@Quantisan OK the README is updated. I also stopped installing boot in the `latest` image.

**Review by Quantisan — APPROVED** [review]
🙇

**Comment by cap10morgan** [comment]
I still need to submit the docker-library PR for this. I’ll try to do that tonight or tomorrow. We’re very close to being able to automate that step… 🤔

**Pull request merged**
