### PR TITLE
Dockerfile templates

### PR DESCRIPTION
**Pull request by cap10morgan**
Alright, I think this and [these changes to the clojure build definition](https://github.com/docker-library/official-images/compare/master...cap10morgan:update-clojure) should work to create leiningen and boot images in a way that is compatible with the official image build system.

All of the non-onbuild Dockerfiles are now generated from the `Dockerfile-boot.template` and `Dockerfile-lein.template` files by the `update.sh` script. If you make a change to either template (such as updating to a new lein or boot version), just run `./update.sh` in the root of the project. The `update.sh` script is modeled after other examples the docker-library maintainers pointed me to, and it seems to require bash 4.x (notably I had to `brew install bash` even on macOS 10.12.2 b/c it ships with bash 3.x).

When / if this is merged, I'll PR the clojure build definition changes to the `docker-library/official-images` repo. Note that it also converts that file to their new format, which is [documented here](https://github.com/docker-library/official-images/tree/da82684a9c2f5ea9d47473888b09d6951789239b).

### CODE REVIEW

**Comment by Quantisan** [comment]
@cap10morgan could you note in README that Bash 4 is needed to run `update.sh`. Otherwise, LTGM. Please merge when you're ok with it. Thanks!

**Comment by Quantisan** [comment]
I like the image tag semantic `clojure:boot` vs `clojure:lein`, etc. Good stuff!

**Comment by cap10morgan** [comment]
[official-images PR](https://github.com/docker-library/official-images/pull/2566) is up

**Comment by cap10morgan** [comment]
And now it's merged. I'll make an announcement on the clojure mailing list.

**Pull request merged**
