### PR TITLE
Add alpine-based build

### PR DESCRIPTION
**Pull request by cap10morgan**
Image size is ~175MB instead of ~660MB.

### CODE REVIEW

**Comment by Quantisan** [comment]
Nice, @cap10morgan! Do you see any downside switching over to this distro?

**Comment by cap10morgan** [comment]
The biggest downside is that it's different so downstream users will need to adjust. I would propose something along the lines of what the upstream java image did:

Build `clojure:lein-[version]-alpine` images and push those to the Docker Hub alongside the ubuntu-based ones for now.

That will give people the ability to opt-in to alpine if they want to. At some point in the future a switch could be announced ahead of time where the ubuntu-based image either gets dropped or moved to a `clojure:lein-[version]-ubuntu` tag and the alpine-based one takes over the `clojure:lein-[version]` tag.

Seem reasonable?

**Comment by Quantisan** [comment]
@cap10morgan sounds good to me. Do you want to be the maintainer for the alpine variant?

**Comment by cap10morgan** [comment]
Sure, I can do that.

**Comment by Quantisan** [comment]
Could you update the info in the Dockerfile, and I've merged your other PR (thanks!), could you rebase that here too? Thanks!

**Comment by cap10morgan** [comment]
@Quantisan How's that?

**Comment by Quantisan** [comment]
@cap10morgan perfect! thank you!

**Comment by cap10morgan** [comment]
Cool, thanks! I issued this PR against the official-images repo: https://github.com/docker-library/official-images/pull/1587

**Comment by Quantisan** [comment]
:+1: 

I was going to refactor out some commands into a shell file so that the 2 versions can share some code

**Comment by cap10morgan** [comment]
OK. Would you like me to close that PR until you do?

**Comment by Quantisan** [comment]
nah, you're right to get it out there ASAP

**Pull request merged**
