### PR TITLE
Feature: build tool entrypoints in openjdk-16+

### LINKED ISSUE #124: Breaking: Make the tool the ENTRYPOINT, and the REPL starter the CMD
I'm considering a potentially breaking change to the official clojure docker images and wanted to get everyone's feedback on it first: For awhile now our images have used `lein repl`, `boot repl`, and `clj` (which defaults to `clj --repl`) as their CMDs and no ENTRYPOINTs.

Meaning if you provide your own command on a docker run, that will become the whole enchilada. E.g. `docker run -ti clojure bash` gets you a bash prompt inside our image. that's useful sometimes.

But these are clojure images, after all, and it would be kind of nice if you could do things like this:
- `docker run clojure:tools-deps -M -e '(+ 1 2)'` and have it print `3`
- `docker run clojure:lein version` and have it print `Leiningen 2.9.6 on Java 11.0.12 OpenJDK 64-Bit Server VM`

The change needed to do this is to put `lein`, `boot`, and `clj` into the ENTRYPOINTs and change the CMDs to `repl`, `repl`, and `-M --repl` (respectively). So then you override just the CMD w/ whatever trails your docker run invocation, but you can still get a bash prompt with `docker run -ti --entrypoint bash clojure`.

### PR DESCRIPTION
**Pull request by cap10morgan**
Closes #124 for openjdk-16+ variants.

Also fixes the rlwrap delay problem in tools-deps variants in a way that is compatible with additional args at container runtime (so you can do e.g. `docker run clojure:tools-deps -M -e '(+ 1 2)'`). And it should be slightly faster to start up too.

### CODE REVIEW

**Comment by dharrigan** [comment]
Echoing the comments on Slack, please consider making `clj` the entrypoint, rather than `lein`. Thank you.

**Comment by cap10morgan** [comment]
@dharrigan's comment is referring to the `clojure:latest` image. It might be worth considering for the image that moves to JDK 17, which will happen after this PR is merged.

**Comment by cap10morgan** [comment]
Looks like there is a little more work to be done in here: https://github.com/docker-library/official-images#consistency

Specifically the official image maintainers want things like `docker run clojure bash` to just work w/o the user needing to understand entrypoints. That seems feasible on tools.deps (b/c it uses hyphenated flags consistently), but I'm not so sure about lein and boot (which do not). Not sure if it would be better to whitelist just `bash` and `sh` for those or what...

But, if we did get that working, it would probably mean this change breaks a lot fewer existing usages. Which would not be a bad thing.

**Comment by cap10morgan** [comment]
I'm hoping a new release of leiningen will come out soon that contains [this change](https://github.com/technomancy/leiningen/pull/2768) so I can consistently implement the logic to skip invoking the build command when someone gives something like `bash` as the command at runtime. Otherwise I would have to special-case leiningen, which I could do, but would like to avoid if possible.

**Comment by Quantisan** [comment]
there's quite a lot of code changes in 56b68076e25659719831c173c842f1d6c4a6a9be 😅, where exactly do you want me to focus my review @cap10morgan ?

on a high level, this PR make sense to me. as you noted, it provides flexibility for end user. Regarding using `clj` as the entrypoint, sounds good to me. Perhaps merge this PR, but don't push to official repo yet, then switch to clj in another PR? For sake of keeping the PR scope.

**Comment by cap10morgan** [comment]
@Quantisan Haha, yeah. No worries. Thanks for the general impressions and advice. I like splitting the clj takeover out into its own PR.

This isn't quite ready for merge yet. I'm waiting on a new (hopefully imminent) leiningen release so I can detect which commands should be passed to it vs. which should override the ENTRYPOINT in a way that's consistent with the other tools (by querying the help for that command and checking the exit status; I had a PR merged to lein to make it behave that way but not released yet).

The Docker official image folks want these images to behave that way ^^^ so that users don't have to understand CMD vs. ENTRYPOINT to e.g. get a bash prompt in an official image container with an ENTRYPOINT.

**Comment by cap10morgan** [comment]
[Leiningen 2.9.8](https://github.com/technomancy/leiningen/releases/tag/2.9.8) just got released so this is unblocked

**Comment by cap10morgan** [comment]
OK I think this is ready for merging finally. I want to land #128 and #130 also after merging this but before we publish new images to Docker Hub. Those will be separate PRs.

Everything look OK to you in here, @Quantisan?

**Comment by cap10morgan** [comment]
Rebased on master

**Review by Quantisan — COMMENTED** [review]
I have nothing particular to add on this PR.

A couple bigger picture thoughts. The Clojure codebase in this is starting to look non-trivial. I'd start thinking about abstractions and structure to the codebase. For example, in dockerfile.clj, using `case` for boot/lein/deps seems like a pattern that can be abstracted out. Perhaps each variant could be a Record and we implement install/prereq/contents as a Protocol?

Second example, `variant` seems like an important data type throughout. Perhaps add a schema to enforce and document what that is.

Just a couple thoughts to perhaps stimulate some design thinking. The actual design, and more importantly, figuring out a first deliverable would be a task on its own.

**Comment by cap10morgan** [comment]
> I have nothing particular to add on this PR.
> 
> A couple bigger picture thoughts. The Clojure codebase in this is starting to look non-trivial. I'd start thinking about abstractions and structure to the codebase. For example, in dockerfile.clj, using `case` for boot/lein/deps seems like a pattern that can be abstracted out. Perhaps each variant could be a Record and we implement install/prereq/contents as a Protocol?

Yeah I like that. Will look into it.

> 
> Second example, `variant` seems like an important data type throughout. Perhaps add a schema to enforce and document what that is.

It has a spec: https://github.com/Quantisan/docker-clojure/blob/09f93abaab24abff0988c80cab1d35e17156d7b4/src/docker_clojure/core.clj#L109-L112

> 
> Just a couple thoughts to perhaps stimulate some design thinking. The actual design, and more importantly, figuring out a first deliverable would be a task on its own.

Good thoughts, thanks. Always good to take a step back and see where things can be improved.

**Pull request merged**
