### PR TITLE
New scripts to help with builds and pushes

### PR DESCRIPTION
**Pull request by cap10morgan**
Also replaces the deprecated `MAINTAINER` Dockerfile directive with the new `LABEL maintainer=` recommendation.

### CODE REVIEW

**Comment by cap10morgan** [comment]
Now that I think about it, we don't ever push these directly do we? So maybe that push script isn't much use.

**Comment by Quantisan** [comment]
@cap10morgan You're right about the push script being redundant. Could you add some instruction to these new scripts in README? Otherwise, LGTM

**Comment by cap10morgan** [comment]
@Quantisan Good suggestion. How does that look?

**Comment by Quantisan** [comment]
@cap10morgan LGTM! Thanks pal!

**Pull request merged**
