### PR TITLE
Update to clojure 1.10.3 and tools deps 1.10.3.814

### PR DESCRIPTION
**Pull request by imrekoszo**
This looked straightforward enough so I went ahead with it.

### CODE REVIEW

**Comment by cap10morgan** [comment]
Thanks for the PR @imrekoszo! We only update to stable releases of tools-deps. The latest of which is currently 1.10.2.796 (see here: https://github.com/clojure/brew-install/blob/1.10.3/CHANGELOG.md).

And you can pull in any version of Clojure itself in your apps running inside the container.

Once there is a stable release of the 1.10.3.x series we'll put out an update with it.

**Comment by imrekoszo** [comment]
Thanks @cap10morgan, I didn't realize that was still marked as prerelease. Perhaps the link you kindly posted is out of sync with https://clojure.org/releases/tools#_releases ? I asked Alex Miller about it on Slack, waiting for his clarification now.

**Comment by cap10morgan** [comment]
@imrekoszo Ah, yeah, looks like there might be some out-of-sync-ness going on there. I bet you're right that that is intended to be a stable release after all.

If Alex confirms I'll reopen this PR.

**Comment by imrekoszo** [comment]
@cap10morgan thank you, that should now be updated. Alex also mentioned there are a few other places to check whether a release os stable https://clojurians.slack.com/archives/C06MAR553/p1616163064127800?thread_ts=1615911301.014400&cid=C06MAR553

**Comment by cap10morgan** [comment]
Thanks @imrekoszo. I'll review this shortly.

**Review by cap10morgan — APPROVED** [review]
Looks good to me! Thanks again @imrekoszo!

**Comment by cap10morgan** [comment]
Official Docker images PR: https://github.com/docker-library/official-images/pull/9822

**Comment by imrekoszo** [comment]
Thank you very much!

**Pull request merged**
